import test from 'node:test';import assert from 'node:assert/strict';import worker from '../worker.mjs';
const bytes=new TextEncoder().encode('0123456789abcdefghij');
const env={ASSETS:{fetch:async req=>new Response(req.method==='HEAD'?null:bytes,{headers:{'Content-Type':'video/mp4','Content-Length':'20','ETag':'"film"'}})}};
async function get(range,extra={}){return worker.fetch(new Request('https://example.test/film.mp4',{headers:{...(range?{Range:range}:{}),...extra}}),env)}
test('Full GET retains the film and advertises byte ranges',async()=>{const r=await get();assert.equal(r.status,200);assert.equal(r.headers.get('Accept-Ranges'),'bytes');assert.equal(await r.text(),'0123456789abcdefghij')});
for(const [range,want,contentRange] of [['bytes=0-3','0123','bytes 0-3/20'],['bytes=15-','fghij','bytes 15-19/20'],['bytes=-4','ghij','bytes 16-19/20'],['bytes=18-99','ij','bytes 18-19/20']])test(range,async()=>{const r=await get(range);assert.equal(r.status,206);assert.equal(r.headers.get('Content-Range'),contentRange);assert.equal(await r.text(),want)});
for(const range of ['bytes=20-','bytes=8-4','bytes=-0'])test('Unsatisfiable '+range,async()=>{const r=await get(range);assert.equal(r.status,416);assert.equal(r.headers.get('Content-Range'),'bytes */20');assert.equal(await r.text(),'')});
test('Mismatched If-Range returns full representation',async()=>{const r=await get('bytes=0-3',{'If-Range':'"old"'});assert.equal(r.status,200);assert.equal((await r.arrayBuffer()).byteLength,20)});
test('Unsupported multi-range safely returns full representation',async()=>{const r=await get('bytes=0-1,4-5');assert.equal(r.status,200)});
test('Retired consulting URL redirects permanently to the consolidated homepage',async()=>{const r=await worker.fetch(new Request('https://airlantern.com/business-process-consulting/?utm_source=legacy'),env);assert.equal(r.status,301);assert.equal(r.headers.get('Location'),'https://airlantern.com/?utm_source=legacy')});
test('Range and redirect responses carry security headers',async()=>{for(const r of [await get('bytes=0-3'),await get('bytes=99-'),await worker.fetch(new Request('https://airlantern.com/projects/'),env)]){assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');assert.match(r.headers.get('Content-Security-Policy'),/object-src 'none'/);assert.match(r.headers.get('Strict-Transport-Security'),/31536000/)}});
test('Film ranges work when ASSETS omits its internal Content-Length',async()=>{const e={ASSETS:{fetch:async()=>new Response(bytes,{headers:{'Content-Type':'video/mp4'}})}};const r=await worker.fetch(new Request('https://airlantern.com/assets/video/lantern-film-50s.b7c52327a38c.mp4',{headers:{Range:'bytes=0-3'}}),e);assert.equal(r.status,206);assert.equal(await r.text(),'0123');assert.equal(r.headers.get('Content-Range'),'bytes 0-3/16323513')});
test('Range streaming stops and cancels upstream after the requested bytes',async()=>{let cancelled=false;let chunks=0;const e={ASSETS:{fetch:async()=>new Response(new ReadableStream({pull(c){chunks++;c.enqueue(new Uint8Array(1024).fill(chunks))},cancel(){cancelled=true}}),{headers:{'Content-Length':'1048576'}})}};const r=await worker.fetch(new Request('https://airlantern.com/film.mp4',{headers:{Range:'bytes=1024-2047'}}),e);const body=new Uint8Array(await r.arrayBuffer());assert.equal(body.length,1024);assert.ok(body.every(v=>v===2));assert.ok(cancelled);assert.ok(chunks<10)});
test('Legacy project URL lands at the current systems section',async()=>{const r=await worker.fetch(new Request('https://airlantern.com/projects/?utm_source=legacy'),env);assert.equal(r.status,301);assert.equal(r.headers.get('Location'),'https://airlantern.com/?utm_source=legacy#systems')});
